.TH "Downloader.h" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Downloader.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIPDL::Downloader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIPDL\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBIPDL::DownloadStatus\fP { \fBIPDL::Complete\fP, \fBIPDL::Incomplete\fP, \fBIPDL::AlreadyExists\fP, \fBIPDL::Unavailable\fP, \fBIPDL::Error\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
