.TH "IPDL" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPDL \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUtil\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAbstractRequest\fP"
.br
.ti -1c
.RI "class \fBCli\fP"
.br
.ti -1c
.RI "class \fBCoreMediaRequest\fP"
.br
.ti -1c
.RI "class \fBDownloader\fP"
.br
.ti -1c
.RI "class \fBGeneralRequest\fP"
.br
.ti -1c
.RI "class \fBIphonePage\fP"
.br
.ti -1c
.RI "class \fBIphoneRequest\fP"
.br
.ti -1c
.RI "class \fBPlaylist\fP"
.br
.ti -1c
.RI "class \fBPlaylistItem\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDownloadStatus\fP { \fBComplete\fP, \fBIncomplete\fP, \fBAlreadyExists\fP, \fBUnavailable\fP, \fBError\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBIPDL::DownloadStatus\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIComplete \fP\fP
.TP
\fB\fIIncomplete \fP\fP
.TP
\fB\fIAlreadyExists \fP\fP
.TP
\fB\fIUnavailable \fP\fP
.TP
\fB\fIError \fP\fP

.PP
Definition at line 13 of file Downloader.h.
.PP
.nf
13 { Complete, Incomplete, AlreadyExists, Unavailable, Error };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
