.TH "IPDL::Cli" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPDL::Cli \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Cli.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCli\fP ()"
.br
.ti -1c
.RI "\fBCli\fP (\fBDownloader\fP &\fBdownloader\fP)"
.br
.ti -1c
.RI "bool \fBget_succeeded\fP ()"
.br
.ti -1c
.RI "void \fBRun\fP (string[] args)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBDownload\fP (string identifier)"
.br
.ti -1c
.RI "void \fBDownloadEnd\fP (\fBDownloadStatus\fP status, string message)"
.br
.ti -1c
.RI "void \fBDownloadProgress\fP (int bytesDownloaded, int total)"
.br
.ti -1c
.RI "void \fBDownloadStart\fP (string filename)"
.br
.ti -1c
.RI "void \fBShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBShowVersion\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBDownloader\fP & \fBdownloader\fP"
.br
.ti -1c
.RI "string \fBlastOutput\fP = ''"
.br
.ti -1c
.RI "bool \fBquiet\fP"
.br
.ti -1c
.RI "bool \fBsucceeded\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file Cli.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IPDL::Cli::Cli (\fBDownloader\fP & downloader)"
.SS "IPDL::Cli::Cli ()"
.SH "Member Function Documentation"
.PP 
.SS "void IPDL::Cli::Download (string identifier)\fC [private]\fP"
.SS "void IPDL::Cli::DownloadEnd (\fBDownloadStatus\fP status, string message)\fC [private]\fP"
.SS "void IPDL::Cli::DownloadProgress (int bytesDownloaded, int total)\fC [private]\fP"
.SS "void IPDL::Cli::DownloadStart (string filename)\fC [private]\fP"
.SS "bool IPDL::Cli::get_succeeded ()"
.SS "void IPDL::Cli::Run (string[] args)"
.SS "void IPDL::Cli::ShowHelp ()\fC [private]\fP"
.SS "void IPDL::Cli::ShowVersion ()\fC [private]\fP"
.SH "Member Data Documentation"
.PP 
.SS "\fBDownloader\fP& \fBIPDL::Cli::downloader\fP\fC [private]\fP"
.PP
Definition at line 15 of file Cli.h.
.SS "string \fBIPDL::Cli::lastOutput\fP = ''\fC [private]\fP"
.PP
Definition at line 19 of file Cli.h.
.SS "bool \fBIPDL::Cli::quiet\fP\fC [private]\fP"
.PP
Definition at line 17 of file Cli.h.
.SS "bool \fBIPDL::Cli::succeeded\fP\fC [private]\fP"
.PP
Definition at line 17 of file Cli.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
