.TH "IPDL::Util" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPDL::Util \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBExtractPid\fP (string url)"
.br
.ti -1c
.RI "string \fBSIFormat\fP (int number, string units)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBSISuffixes\fP [] = { '', 'K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y' }"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "string IPDL::Util::ExtractPid (string url)"
.SS "string IPDL::Util::SIFormat (int number, string units)"
.SH "Variable Documentation"
.PP 
.SS "string \fBIPDL::Util::SISuffixes\fP[] = { '', 'K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y' }"
.PP
Definition at line 11 of file Util.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
