.TH "IPDL::GeneralRequest" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPDL::GeneralRequest \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Request.h>\fP
.PP
Inherits \fBIPDL::AbstractRequest\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGeneralRequest\fP (string \fBurl\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetResponseStream\fP (ResponseStreamHandler streamHandler)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file Request.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IPDL::GeneralRequest::GeneralRequest (string url)"
.SH "Member Function Documentation"
.PP 
.SS "void IPDL::GeneralRequest::GetResponseStream (ResponseStreamHandler streamHandler)\fC [protected]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
