.TH "IPDL::IphonePage" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPDL::IphonePage \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IphonePage.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIphonePage\fP (string source)"
.br
.ti -1c
.RI "string \fBget_EmbeddedMediaUrl\fP ()"
.br
.ti -1c
.RI "string \fBget_FileExtension\fP ()"
.br
.ti -1c
.RI "bool \fBget_IsAvailable\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBUrl\fP (string pid)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBInit\fP (string source)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "string \fBdocument\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "static string \fBurlPrefix\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file IphonePage.h.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IPDL::IphonePage::IphonePage (string source)"
.SH "Member Function Documentation"
.PP 
.SS "string IPDL::IphonePage::get_EmbeddedMediaUrl ()"
.SS "string IPDL::IphonePage::get_FileExtension ()"
.SS "bool IPDL::IphonePage::get_IsAvailable ()"
.SS "void IPDL::IphonePage::Init (string source)\fC [private]\fP"
.SS "static string IPDL::IphonePage::Url (string pid)\fC [static]\fP"
.SH "Member Data Documentation"
.PP 
.SS "string \fBIPDL::IphonePage::document\fP\fC [private]\fP"
.PP
Definition at line 17 of file IphonePage.h.
.SS "string \fBIPDL::IphonePage::urlPrefix\fP\fC [static, private]\fP"
.PP
Definition at line 15 of file IphonePage.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
