.TH "IPDL::PlaylistItem" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IPDL::PlaylistItem \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Playlist.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBAlternate\fP"
.br
.ti -1c
.RI "string \fBGroup\fP"
.br
.ti -1c
.RI "string \fBIdentifier\fP"
.br
.ti -1c
.RI "string \fBKind\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 18 of file Playlist.h.
.SH "Member Data Documentation"
.PP 
.SS "string \fBIPDL::PlaylistItem::Alternate\fP"
.PP
Definition at line 23 of file Playlist.h.
.SS "string \fBIPDL::PlaylistItem::Group\fP"
.PP
Definition at line 22 of file Playlist.h.
.SS "string \fBIPDL::PlaylistItem::Identifier\fP"
.PP
Definition at line 21 of file Playlist.h.
.SS "string \fBIPDL::PlaylistItem::Kind\fP"
.PP
Definition at line 20 of file Playlist.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
