.TH "Playlist.h" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Playlist.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'pugixml.hpp'\fP
.br
\fC#include <exception>\fP
.br
\fC#include <stddef.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIPDL::Playlist\fP"
.br
.ti -1c
.RI "class \fBIPDL::PlaylistItem\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIPDL\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
