.TH "Util.h" 3 "26 Dec 2010" "Version 0.0.1" "airplug-provider-iplayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBIPDL\fP"
.br
.ti -1c
.RI "namespace \fBIPDL::Util\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "string \fBIPDL::Util::ExtractPid\fP (string url)"
.br
.ti -1c
.RI "string \fBIPDL::Util::SIFormat\fP (int number, string units)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBIPDL::Util::SISuffixes\fP [] = { '', 'K', 'M', 'G', 'T', 'P', 'E', 'Z', 'Y' }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for airplug-provider-iplayer from the source code.
